# mediamtx.yml
paths:
  all_others:

# --- WebRTC Settings ---
webrtc: yes
webrtcAddress: :8889
webrtcEncryption: no
webrtcLocalUDPAddress: :10000
webrtcIPsFromInterfaces: true
webrtcAdditionalHosts: [192.168.1.37]

# --- API Settings ---
api: true
apiAddress: :9997
apiAllowOrigins: ['*']

# --- Authentication Settings ---
authInternalUsers:
  # 1. อนุญาตให้ทุกคน Publish และ Read ได้ (สำหรับโดรนและคนดู)
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
      - action: read
      - action: playback

  # 2. อนุญาตให้เรียก API ได้จากทุกที่ (สำหรับ Controller ของคุณ)
  - user: any
    pass:
    ips: [] 
    permissions:
      - action: api
      - action: metrics
      - action: pprof